// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDho0BAWUdBDmL4bxQ8eq-lJTudRauCsIg',
    appId: '1:254232052405:web:ab0e6d6fdfdf0a334d74fc',
    messagingSenderId: '254232052405',
    projectId: 'igm-mmgsll',
    authDomain: 'igm-mmgsll.firebaseapp.com',
    databaseURL: 'https://igm-mmgsll-default-rtdb.firebaseio.com',
    storageBucket: 'igm-mmgsll.firebasestorage.app',
    measurementId: 'G-SXG28JCTYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCImmveNL8Ewdkvb4tRzjRNYgA6y0LNFfc',
    appId: '1:254232052405:android:309789a773b08d3d4d74fc',
    messagingSenderId: '254232052405',
    projectId: 'igm-mmgsll',
    databaseURL: 'https://igm-mmgsll-default-rtdb.firebaseio.com',
    storageBucket: 'igm-mmgsll.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxG4GF1d7nhRG-fMoWv7Bm6_fQsr8RBNk',
    appId: '1:254232052405:ios:2e7b76d55190f0484d74fc',
    messagingSenderId: '254232052405',
    projectId: 'igm-mmgsll',
    databaseURL: 'https://igm-mmgsll-default-rtdb.firebaseio.com',
    storageBucket: 'igm-mmgsll.firebasestorage.app',
    iosBundleId: 'com.example.igm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxG4GF1d7nhRG-fMoWv7Bm6_fQsr8RBNk',
    appId: '1:254232052405:ios:2e7b76d55190f0484d74fc',
    messagingSenderId: '254232052405',
    projectId: 'igm-mmgsll',
    databaseURL: 'https://igm-mmgsll-default-rtdb.firebaseio.com',
    storageBucket: 'igm-mmgsll.firebasestorage.app',
    iosBundleId: 'com.example.igm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDho0BAWUdBDmL4bxQ8eq-lJTudRauCsIg',
    appId: '1:254232052405:web:2c4d74e95dc2b2414d74fc',
    messagingSenderId: '254232052405',
    projectId: 'igm-mmgsll',
    authDomain: 'igm-mmgsll.firebaseapp.com',
    databaseURL: 'https://igm-mmgsll-default-rtdb.firebaseio.com',
    storageBucket: 'igm-mmgsll.firebasestorage.app',
    measurementId: 'G-TFXDYFW3GL',
  );
}
