import 'dart:developer';

import 'package:refreshed/refreshed.dart';

class ImportBLXMLGeneration {
  final List<RxString> years;
  final List<RxString> feederVesselNames;
  final List<RxString> fevRotationNos;
  final List<RxString> fvVoys;
  final List<RxString> netMTs;
  final List<RxString> departureDates;
  final List<RxString> depCodes;
  final List<RxString> flagNames;
  final List<RxString> arrivalDates;
  final List<RxString> berthingDates;
  final List<RxString> portOfShipments;
  final List<RxString> flags;

  final List<RxString> lineNos;
  final List<RxString> contPrefixes;
  final List<RxString> contNos;
  final List<RxString> sizes;
  final List<RxString> contTypes;
  final List<RxString> isoCodes;
  final List<RxString> qtys;
  final List<RxString> uoms;
  final List<RxString> weightKgms;
  final List<RxString> contVolumes;
  final List<RxString> vgmQtys;
  final List<RxString> cbms;
  final List<RxString> sealNos;
  final List<RxString> imcos;
  final List<RxString> uns;
  final List<RxString> statuses;
  final List<RxString> loadPortDts;
  final List<RxString> remarks;
  final List<RxString> parts;
  final List<RxString> offDocks;
  final List<RxString> commoCodes;
  final List<RxString> perishables;

  final List<RxString> portOfLanding;
  final List<RxString> slNo;
  final List<RxString> blLineNo;
  final List<RxString> blNo;
  final List<RxString> fcl;
  final List<RxString> fclQty;
  final List<RxString> lcl;
  final List<RxString> lclConsolidated;
  final List<RxString> consigneeCode;
  final List<RxString> consignee;
  final List<RxString> consigneeAddress;
  final List<RxString> exporter;
  final List<RxString> blRemarks;
  final List<RxString> notifyCode;
  final List<RxString> notifyParty;
  final List<RxString> notifyAddress;
  final List<RxString> exporterAddress;
  final List<RxString> placeOfUnload;
  final List<RxString> blNature;
  final List<RxString> blTypeCode;
  final List<RxString> blLoadPortDt;
  final List<RxString> marks;
  final List<RxString> quantity;
  final List<RxString> quantity2;
  final List<RxString> commodity;
  final List<RxString> dgStatus;


  ImportBLXMLGeneration({required this.years, required this.feederVesselNames,
    required this.fevRotationNos,
    required this.fvVoys, required this.netMTs, required this.departureDates,
    required this.depCodes,
    required this.flagNames, required this.arrivalDates,
    required this.berthingDates,
    required this.portOfShipments, required this.flags, required this.lineNos,
    required this.contPrefixes,
    required this.contNos, required this.sizes, required this.contTypes,
    required this.isoCodes, required this.qtys,
    required this.uoms, required this.weightKgms, required this.contVolumes,
    required this.vgmQtys, required this.cbms,
    required this.sealNos, required this.imcos, required this.uns,
    required this.statuses, required this.loadPortDts,
    required this.remarks, required this.parts, required this.offDocks,
    required this.commoCodes,
    required this.perishables, required this.portOfLanding,
    required this.slNo,
    required this.blLineNo, required this.blNo,
    required this.fcl, required this.fclQty,
    required this.lcl, required this.lclConsolidated,
    required this.consigneeCode,
    required this.consignee, required this.consigneeAddress,
    required this.exporter,
    required this.blRemarks, required this.notifyCode,
    required this.notifyParty,
    required this.notifyAddress, required this.exporterAddress,
    required this.placeOfUnload,
    required this.blNature, required this.blTypeCode,
    required this.blLoadPortDt,
    required this.marks, required this.quantity,
    required this.quantity2, required this.commodity,
    required this.dgStatus});

  generateXML() {
    final xml = '''<?xml version="1.0" encoding="WINDOWS-1252"?>
      <!-- Generated by Oracle Reports version 10.1.2.0.2 -->
      <Awmds>
        <General_segment>
          <General_segment_id>
            <Customs_office_code>305</Customs_office_code>
            <Voyage_number>${fevRotationNos[0].value}</Voyage_number>
            <Date_of_departure>${departureDates[0].value}</Date_of_departure>
            <Date_of_arrival>${arrivalDates[0].value}</Date_of_arrival>
          </General_segment_id>
          <Totals_segment>
            <Total_number_of_bols>1</Total_number_of_bols>
            <Total_number_of_packages>${qtys[0].value}</Total_number_of_packages>
            <Total_number_of_containers>1</Total_number_of_containers>
            <Total_gross_mass>${weightKgms[0].value}</Total_gross_mass>
          </Totals_segment>
          <Transport_information>
            <Carrier>
              <Carrier_code>301063243</Carrier_code>
              <Carrier_name>MM SEAWAYS LTD.</Carrier_name>
              <Carrier_address>&quot;Portland MAM Tower&quot; 226 Strand Road, Bangla Bazar, CTG.</Carrier_address>
            </Carrier>
            <Mode_of_transport_code>1</Mode_of_transport_code>
            <Identity_of_transporter>HR SAHARE</Identity_of_transporter>
            <Nationality_of_transporter_code>${flags[0].value}</Nationality_of_transporter_code>
          </Transport_information>
          <Load_unload_place>
            <Place_of_departure_code>${depCodes[0].value}</Place_of_departure_code>
            <Place_of_destination_code>BDCGP</Place_of_destination_code>
          </Load_unload_place>
        </General_segment>
        <Bol_segment>
          <Bol_id>
            <Bol_reference>ARGJEACGP2402545</Bol_reference>
            <Line_number>1</Line_number>
            <Bol_nature>${blNature[0].value}</Bol_nature>
            <Bol_type_code>${blTypeCode[0].value}</Bol_type_code>
            <DG_status>${dgStatus[0].value}</DG_status>
          </Bol_id>
          <Consolidated_Cargo>${lclConsolidated[0].value}</Consolidated_Cargo>
          <Load_unload_place>
            <Port_of_origin_code>${blLoadPortDt[0].value}</Port_of_origin_code>
            <Place_of_unloading_code>${placeOfUnload[0].value}</Place_of_unloading_code>
          </Load_unload_place>
          <Traders_segment>
            <Carrier>
              <Carrier_code>301063243</Carrier_code>
              <Carrier_name>MM SEAWAYS LTD.</Carrier_name>
              <Carrier_address>&quot;Portland MAM Tower&quot; 226 Strand Road, Bangla Bazar, CTG.</Carrier_address>
            </Carrier>
            <Shipping_Agent>
              <Shipping_Agent_code>LTS</Shipping_Agent_code>
              <Shipping_Agent_name>LANDT CONTAINER(1999) PTE LTD</Shipping_Agent_name>
            </Shipping_Agent>
            <Exporter>
              <Exporter_name>${exporter[0].value}</Exporter_name>
              <Exporter_address>${exporterAddress[0].value}</Exporter_address>
            </Exporter>
            <Notify>
              <Notify_code>${notifyCode[0].value}</Notify_code>
              <Notify_name>${notifyParty[0].value}</Notify_name>
              <Notify_address>${notifyAddress[0].value}</Notify_address>
            </Notify>
            <Consignee>
              <Consignee_code>${consigneeCode[0].value}</Consignee_code>
              <Consignee_name>${consignee[0].value}</Consignee_name>
              <Consignee_address>${consigneeAddress[0].value}</Consignee_address>
            </Consignee>
          </Traders_segment>
          <ctn_segment>
            <Ctn_reference>${contPrefixes[0].value}${contNos[0].value}</Ctn_reference>
            <Number_of_packages>${qtys[0].value}</Number_of_packages>
            <Type_of_container>${contTypes[0].value}</Type_of_container>
            <Status>${statuses[0].value}</Status>
            <Seal_number>${sealNos[0].value}</Seal_number>
            <IMCO>${imcos[0].value}</IMCO>
            <UN>${uns[0].value}</UN>
            <Ctn_location>${portOfLanding[0].value}</Ctn_location>
            <Commodity_code>${commoCodes[0].value}</Commodity_code>
            <Gross_weight>${weightKgms[0].value}</Gross_weight>
            <Verified_Gross_Mass>${vgmQtys[0].value}</Verified_Gross_Mass>
          </ctn_segment>
          <Goods_segment>
            <Number_of_packages>${quantity[0].value}</Number_of_packages>
            <Package_type_code>${quantity2[0].value}</Package_type_code>
            <Gross_mass>${weightKgms[0].value}</Gross_mass>
            <Shipping_marks>${marks[0].value}</Shipping_marks>
            <Goods_description>${commodity[0].value}</Goods_description>
            <Volume_in_cubic_meters>${contVolumes[0].value}</Volume_in_cubic_meters>
            <Num_of_ctn_for_required required this_bol>1</Num_of_ctn_for_required required this_bol>
            <Remarks>${remarks[0].value}</Remarks>
          </Goods_segment>
          <Value_segment>
            <Freight_segment>
              <Freight_value>0</Freight_value>
              <Freight_currency>xxx</Freight_currency>
            </Freight_segment>
          </Value_segment>
        </Bol_segment>
      </Awmds>''';

    log(xml.toString());
    return xml.toString();
  }

}
