import 'dart:developer';
import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:igm/db%20handler/db_logics.dart';
import 'package:refreshed/refreshed.dart';

class ImportBLXMLGeneration {
  final List<RxString> years;
  final List<RxString> feederVesselNames;
  final List<RxString> fevRotationNos;
  final List<RxString> fvVoys;
  final List<RxString> netMTs;
  final List<RxString> departureDates;
  final List<RxString> depCodes;
  final List<RxString> flagNames;
  final List<RxString> arrivalDates;
  final List<RxString> berthingDates;
  final List<RxString> portOfShipments;
  final List<RxString> flags;

  final List<List<RxString>> lineNos;
  final List<List<RxString>> contPrefixes;
  final List<List<RxString>> contNos;
  final List<List<RxString>> sizes;
  final List<List<RxString>> contTypes;
  final List<List<RxString>> isoCodes;
  final List<List<RxString>> qtys;
  final List<List<RxString>> uoms;
  final List<List<RxString>> weightKgms;
  final List<List<RxString>> contVolumes;
  final List<List<RxString>> vgmQtys;
  final List<List<RxString>> cbms;
  final List<List<RxString>> sealNos;
  final List<List<RxString>> imcos;
  final List<List<RxString>> uns;
  final List<List<RxString>> statuses;
  final List<List<RxString>> loadPortDts;
  final List<List<RxString>> remarks;
  final List<List<RxString>> parts;
  final List<List<RxString>> offDocks;
  final List<List<RxString>> commoCodes;
  final List<List<RxString>> perishables;

  final List<RxString> portOfLanding;
  final List<RxString> slNo;
  final List<RxString> blLineNo;
  final List<RxString> blNo;
  final List<RxString> fcl;
  final List<RxString> fclQty;
  final List<RxString> lcl;
  final List<RxString> lclConsolidated;
  final List<RxString> consigneeCode;
  final List<RxString> consignee;
  final List<RxString> consigneeAddress;
  final List<RxString> exporter;
  final List<RxString> blRemarks;
  final List<RxString> notifyCode;
  final List<RxString> notifyParty;
  final List<RxString> notifyAddress;
  final List<RxString> exporterAddress;
  final List<RxString> placeOfUnload;
  final List<RxString> blNature;
  final List<RxString> blTypeCode;
  final List<RxString> blLoadPortDt;
  final List<RxString> marks;
  final List<RxString> quantity;
  final List<RxString> quantity2;
  final List<RxString> commodity;
  final List<RxString> dgStatus;

  ImportBLXMLGeneration({
    required this.years,
    required this.feederVesselNames,
    required this.fevRotationNos,
    required this.fvVoys,
    required this.netMTs,
    required this.departureDates,
    required this.depCodes,
    required this.flagNames,
    required this.arrivalDates,
    required this.berthingDates,
    required this.portOfShipments,
    required this.flags,
    required this.lineNos,
    required this.contPrefixes,
    required this.contNos,
    required this.sizes,
    required this.contTypes,
    required this.isoCodes,
    required this.qtys,
    required this.uoms,
    required this.weightKgms,
    required this.contVolumes,
    required this.vgmQtys,
    required this.cbms,
    required this.sealNos,
    required this.imcos,
    required this.uns,
    required this.statuses,
    required this.loadPortDts,
    required this.remarks,
    required this.parts,
    required this.offDocks,
    required this.commoCodes,
    required this.perishables,
    required this.portOfLanding,
    required this.slNo,
    required this.blLineNo,
    required this.blNo,
    required this.fcl,
    required this.fclQty,
    required this.lcl,
    required this.lclConsolidated,
    required this.consigneeCode,
    required this.consignee,
    required this.consigneeAddress,
    required this.exporter,
    required this.blRemarks,
    required this.notifyCode,
    required this.notifyParty,
    required this.notifyAddress,
    required this.exporterAddress,
    required this.placeOfUnload,
    required this.blNature,
    required this.blTypeCode,
    required this.blLoadPortDt,
    required this.marks,
    required this.quantity,
    required this.quantity2,
    required this.commodity,
    required this.dgStatus,
  });

  double totalGrossMass = 0.0;

  int total_qty = 0;

  final dbHelper = DatabaseLogics();

  Future<void> saveFile(String fileName, String filePath) async {
    await dbHelper.insertFile(fileName, filePath);
  }


  getTotalQty() {
    print("object: ${quantity[0]}");
    for(var v in quantity) {
        total_qty += int.parse(v.value.isEmpty ? "0" : v.value);
    }
    return total_qty;
  }

  generateXML() {
    final xml =
        '''
<?xml version="1.0" encoding="WINDOWS-1252"?>
<!-- Generated by Aileron version 1.0.0.0.1 -->
<Awmds>
  <General_segment>
    <General_segment_id>
      <Customs_office_code>301</Customs_office_code>
      <Voyage_number>${fvVoys[0].value}</Voyage_number>
      <Date_of_departure>${departureDates[0].value}</Date_of_departure>
      <Date_of_arrival>${arrivalDates[0].value}</Date_of_arrival>
    </General_segment_id>
    <Totals_segment>
      <Total_number_of_bols>${blLineNo.length.toString()}</Total_number_of_bols>
      <Total_number_of_packages>${getTotalQty()}</Total_number_of_packages>
      <Total_number_of_containers>${contNos.length.toString()}</Total_number_of_containers>
      <Total_gross_mass>${weightKgms[0][0].value}</Total_gross_mass>
    </Totals_segment>
    <Transport_information>
      <Carrier>
        <Carrier_code>301063243</Carrier_code>
        <Carrier_name>MM SEAWAYS LTD.</Carrier_name>
        <Carrier_address>&quot;Portland MAM Tower&quot; 226 Strand Road, Bangla Bazar, CTG.</Carrier_address>
      </Carrier>
      <Mode_of_transport_code>1</Mode_of_transport_code>
      <Identity_of_transporter>${feederVesselNames[0].value}</Identity_of_transporter>
      <Nationality_of_transporter_code>${flags[0].value}</Nationality_of_transporter_code>
    </Transport_information>
    <Load_unload_place>
      <Place_of_departure_code>${depCodes[0].value}</Place_of_departure_code>
      <Place_of_destination_code>BDCGP</Place_of_destination_code>
    </Load_unload_place>
  </General_segment>
  <Bol_segment>
    <Bol_id>
      <Bol_reference>${blNo[0].value}</Bol_reference>
      <Line_number>${slNo[0].value}</Line_number>
      <Bol_nature>${blNature[0].value}</Bol_nature>
      <Bol_type_code>${blTypeCode[0].value}</Bol_type_code>
      <DG_status>${dgStatus[0].value == "YES" ? "DG" : ""}</DG_status>
    </Bol_id>
    <Consolidated_Cargo>${lcl[0].value.isEmpty ? "0" : lclConsolidated[0].value}</Consolidated_Cargo>
    <Load_unload_place>
      <Port_of_origin_code>${blLoadPortDt[0].value}</Port_of_origin_code>
      <Place_of_unloading_code>${placeOfUnload[0].value}</Place_of_unloading_code>
    </Load_unload_place>
    <Traders_segment>
      <Carrier>
        <Carrier_code>301093439</Carrier_code>
        <Carrier_name>NOBLE SHIPPING LINE</Carrier_name>
        <Carrier_address>PORTLAND M A M TOWER(13TH FLOOR),STRAND ROAD,BANGLABAZAR,CHATTOGRAM</Carrier_address>
      </Carrier>
      <Shipping_Agent>
        <Shipping_Agent_code>KCP</Shipping_Agent_code>
        <Shipping_Agent_name>KING CHARTERING AND PROJECT</Shipping_Agent_name>
      </Shipping_Agent>
      <Exporter>
        <Exporter_name>${exporter[0].value}</Exporter_name>
        <Exporter_address>${exporterAddress[0].value}</Exporter_address>
      </Exporter>
      <Notify>
        <Notify_code>${notifyCode[0].value}</Notify_code>
        <Notify_name>${notifyParty[0].value}</Notify_name>
        <Notify_address>${notifyAddress[0].value}</Notify_address>
      </Notify>
      <Consignee>
        <Consignee_code>${consigneeCode[0].value}</Consignee_code>
        <Consignee_name>${consignee[0].value}</Consignee_name>
        <Consignee_address>${consigneeAddress[0].value}</Consignee_address>
      </Consignee>
    </Traders_segment>
    <ctn_segment>
      <Ctn_reference>${contPrefixes[0][0].value}${contNos[0][0].value}</Ctn_reference>
      <Number_of_packages>${qtys[0][0].value}</Number_of_packages>
      <Type_of_container>${isoCodes[0][0].value}</Type_of_container>
      <Status>${statuses[0][0].value}</Status>
      <Seal_number>${sealNos[0][0].value}</Seal_number>
      <IMCO>${imcos[0][0].value}</IMCO>
      <UN>${uns[0][0].value}</UN>
      <Ctn_location>${portOfLanding[0].value}</Ctn_location>
      <Commodity_code>${commoCodes[0][0].value}</Commodity_code>
      <Gross_weight>${weightKgms[0][0].value}</Gross_weight>
      <Verified_Gross_Mass>${vgmQtys[0][0].value}</Verified_Gross_Mass>
    </ctn_segment>
    <Goods_segment>
      <Number_of_packages>${quantity[0].value}</Number_of_packages>
      <Package_type_code>${quantity2[0].value}</Package_type_code>
      <Gross_mass>${weightKgms[0][0].value}</Gross_mass>
      <Shipping_marks>${marks[0].value}</Shipping_marks>
      <Goods_description>${commodity[0].value}</Goods_description>
      <Volume_in_cubic_meters>0</Volume_in_cubic_meters>
      <Num_of_ctn_for_required>1</Num_of_ctn_for_required>
      <Remarks>${remarks[0][0].value}</Remarks>
    </Goods_segment>
    <Value_segment>
      <Freight_segment>
        <Freight_value>0</Freight_value>
        <Freight_currency>xxx</Freight_currency>
      </Freight_segment>
    </Value_segment>
  </Bol_segment>
</Awmds>''';

    log(xml.toString());
    return xml.toString();
  }

  dynamic getGrossMass(int index) {
    var totalMass = 0;
    for (var v in weightKgms[index]) {
      totalMass += int.parse(v.value);
    }

    return totalMass.toString();
  }

  dynamic getAllContainerInfoForSpecificBL(int index) {

    print("blufff $qtys");

    String ctns = "";

    for (int i = 0; i < contNos[index].length; i++) {
      if (i != 0) {
        ctns += "\n";
      }

      ctns +=
          """
<ctn_segment>
  <Ctn_reference>${contPrefixes[index][i].value}${contNos[index][i].value}</Ctn_reference>
  <Number_of_packages>${qtys[index][i].value}</Number_of_packages>
  <Type_of_container>${isoCodes[index][i].value}</Type_of_container>
  <Status>${statuses[index][i].value.isEmpty ? "FCL" : statuses[index][i].value}</Status>
  <Seal_number>${sealNos[index][i].value}</Seal_number>
  <IMCO>${imcos[index][i].value}</IMCO>
  <UN>${uns[index][i].value}</UN>
  <Ctn_location>${offDocks[index][i].value}</Ctn_location>
  <Commodity_code>${commoCodes[index][i].value}</Commodity_code>
  <Gross_weight>${weightKgms[index][i].value}</Gross_weight>
  <Verified_Gross_Mass>${vgmQtys[index][i].value}</Verified_Gross_Mass>
</ctn_segment>""";
    }
    return ctns;
  }

  dynamic getCombinedMass(int index) {
    double grossMass = 0;

    for (int i = 0; i < weightKgms[index].length; i++) {
      if (weightKgms[index][i].value.isNotEmpty &&
          double.tryParse(weightKgms[index][i].value) != null) {
        grossMass += double.parse(weightKgms[index][i].value);
      }
    }

    totalGrossMass += grossMass;

    return grossMass.toString();
  }

  dynamic getCombinedContainerVolume(int index) {
    double grossVolume = 0.0;

    for (int i = 0; i < contVolumes[index].length; i++) {
      if (contVolumes[index][i].value.isNotEmpty &&
          double.tryParse(contVolumes[index][i].value) != null) {
        grossVolume += double.parse(contVolumes[index][i].value);
      }
    }

    return grossVolume.toString();
  }

  dynamic prepareMultiBLSection(company, mloCode, mloName) {
    print("wtf $dgStatus");
    List totalBls = blNo.where((v) => v.isNotEmpty).toList();
    print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n${totalBls.length}");
    String BLs = "";
    for (int i = 0; i < totalBls.length; i++) {
      if (i != 0) {
        BLs += "\n";
      }
      BLs +=
          """
<Bol_segment>
  <Bol_id>
    <Bol_reference>${blNo[i].value}</Bol_reference>
    <Line_number>${slNo[i].value}</Line_number>
    <Bol_nature>${blNature[i].value}</Bol_nature>
    <Bol_type_code>${blTypeCode[i].value}</Bol_type_code>
    <DG_status>${dgStatus[i].value == "YES" || dgStatus[i].value == "Yes" ? "DG" : ""}</DG_status>
  </Bol_id>
  <Consolidated_Cargo>${lclConsolidated[i].value.isEmpty || lcl[i].value.isEmpty ? "0" : "1"}</Consolidated_Cargo>
  <Load_unload_place>
    <Port_of_origin_code>${blLoadPortDt[i].value}</Port_of_origin_code>
      <Place_of_unloading_code>${placeOfUnload[i].value}</Place_of_unloading_code>
  </Load_unload_place>
  <Traders_segment>
    <Carrier>
      <Carrier_code>301093439</Carrier_code>
      <Carrier_name>$company</Carrier_name>
      <Carrier_address>PORTLAND M A M TOWER(13TH FLOOR),STRAND ROAD,BANGLABAZAR,CHATTOGRAM</Carrier_address>
    </Carrier>
    <Shipping_Agent>
      <Shipping_Agent_code>$mloCode</Shipping_Agent_code>
        <Shipping_Agent_name>$mloName</Shipping_Agent_name>
    </Shipping_Agent>
    <Exporter>
      <Exporter_name>${exporter[i].value}</Exporter_name>
      <Exporter_address>${exporterAddress[i].value}</Exporter_address>
    </Exporter>
    <Notify>
      <Notify_code>${notifyCode[i].value}</Notify_code>
      <Notify_name>${notifyParty[i].value}</Notify_name>
      <Notify_address>${notifyAddress[i].value}</Notify_address>
    </Notify>
    <Consignee>
      <Consignee_code>${consigneeCode[i].value}</Consignee_code>
      <Consignee_name>${consignee[i].value}</Consignee_name>
      <Consignee_address>${consigneeAddress[i].value}</Consignee_address>
    </Consignee>
  </Traders_segment>
  ${getAllContainerInfoForSpecificBL(i)}
  <Goods_segment>
    <Number_of_packages>${quantity[i].value}</Number_of_packages>
    <Package_type_code>${quantity2[i].value}</Package_type_code>
    <Gross_mass>${getCombinedMass(i)}</Gross_mass>
    <Shipping_marks>${marks[i].value}</Shipping_marks>
    <Goods_description>${commodity[i].value}</Goods_description>
    <Volume_in_cubic_meters>0</Volume_in_cubic_meters>
    <Num_of_ctn_for_this_bol>${contNos[i].length.toString()}</Num_of_ctn_for_this_bol>
    <Remarks></Remarks>
  </Goods_segment>
  <Value_segment>
    <Freight_segment>
      <Freight_value>0</Freight_value>
      <Freight_currency>xxx</Freight_currency>
    </Freight_segment>
  </Value_segment>
</Bol_segment>""";
    }

    return BLs;
  }

  getGrossMassAsPerWeightKGM() {
    double totalMass = 0;
    for (var v in weightKgms) {
      for (var m in v) {
        if(m.value.isNotEmpty) {
          totalMass += double.parse(m.value);
        }
      }
    }

    return totalMass;
}

  dynamic generateMultiBL(String company, String mloCode, String mloName) async {

    List totalBls = blNo.where((v) => v.isNotEmpty).toList();

    contPrefixes.removeWhere(
          (e) => e.isEmpty || e.every((x) => x.toString().trim().isEmpty),
    );

    int totalContainers = 0;

    for(int i = 0; i < contPrefixes.length; i++) {
      totalContainers += contPrefixes[i].length;
    }

    // contPrefixes.remove([]);
    print("uuu$totalContainers '$contPrefixes'");
    var structure =
        """
<?xml version="1.0" encoding="WINDOWS-1252"?>
<!-- Generated by Aileron version 1.0.0.0.1 -->
<Awmds>
  <General_segment>
    <General_segment_id>
      <Customs_office_code>301</Customs_office_code>
      <Voyage_number>${fvVoys[0].value}</Voyage_number>
      <Date_of_departure>${departureDates[0].value}</Date_of_departure>
      <Date_of_arrival>${arrivalDates[0].value}</Date_of_arrival>
    </General_segment_id>
    <Totals_segment>
      <Total_number_of_bols>${totalBls.length}</Total_number_of_bols>
      <Total_number_of_packages>${getTotalQty()}</Total_number_of_packages>
      <Total_number_of_containers>$totalContainers</Total_number_of_containers>
      <Total_gross_mass>${getGrossMassAsPerWeightKGM()}</Total_gross_mass>
    </Totals_segment>
    <Transport_information>
      <Carrier>
        <Carrier_code>301093439</Carrier_code>
        <Carrier_name>$company</Carrier_name>
        <Carrier_address>PORTLAND M A M TOWER(13TH FLOOR),STRAND ROAD,BANGLABAZAR,CHATTOGRAM</Carrier_address>
      </Carrier>
      <Mode_of_transport_code>1</Mode_of_transport_code>
      <Identity_of_transporter>${feederVesselNames[0].value}</Identity_of_transporter>
      <Nationality_of_transporter_code>${flags[0].value}</Nationality_of_transporter_code>
    </Transport_information>
    <Load_unload_place>
      <Place_of_departure_code>${depCodes[0].value}</Place_of_departure_code>
      <Place_of_destination_code>BDCGP</Place_of_destination_code>
    </Load_unload_place>
  </General_segment>
  ${prepareMultiBLSection(company, mloCode, mloName)}
</Awmds>
""";

    log(structure);
    try {
      // 1. Generate the XML content by calling the helper
      String xmlContent = structure;
      String fileName = 'MAN301093439_${DateTime.now().day < 10 ? "0${DateTime.now().day}" : DateTime.now().day}${DateTime.now().month}${DateTime.now().year}${DateTime.now().hour}${DateTime.now().minute}${DateTime.now().second}.xml';

      // 2. Use file_picker to open a "Save As..." dialog
      String? outputFile = await FilePicker.platform.saveFile(
        dialogTitle: 'Save Your XML File',
        fileName: fileName, // Suggest a unique filename
        type: FileType.custom,
        allowedExtensions: ['xml'],
      );

      // 3. If the user selected a path (didn't cancel)
      if (outputFile != null) {
        final file = File(outputFile);

        // 4. Write the XML string to the selected file path
        File xmlFile = await file.writeAsString(xmlContent);

        // 5. (Optional) Show a success message
        debugPrint('XML saved successfully to ${file.path}');
        saveFile(fileName, file.path);
      } else {
        debugPrint('User canceled the save dialog.');
      }

    } catch (e) {
      debugPrint('An error occurred during file save: $e');
    }
  }
}

/**
 *
    <Bol_segment>
    <Bol_id>
    <Bol_reference>${blNo[0].value}</Bol_reference>
    <Line_number>${blLineNo[0].value}</Line_number>
    <Bol_nature>${blNature[0].value}</Bol_nature>
    <Bol_type_code>${blTypeCode[0].value}</Bol_type_code>
    <DG_status>${dgStatus[0].value}</DG_status>
    </Bol_id>
    <Consolidated_Cargo>${lclConsolidated[0].value}</Consolidated_Cargo>
    <Load_unload_place>
    <Port_of_origin_code>${blLoadPortDt[0].value}</Port_of_origin_code>
    <Place_of_unloading_code>${placeOfUnload[0].value}</Place_of_unloading_code>
    </Load_unload_place>
    <Traders_segment>
    <Carrier>
    <Carrier_code>301093439</Carrier_code>
    <Carrier_name>NOBLE SHIPPING LINE</Carrier_name>
    <Carrier_address>PORTLAND M A M TOWER(13TH FLOOR),STRAND ROAD,BANGLABAZAR,CHATTOGRAM</Carrier_address>
    </Carrier>
    <Shipping_Agent>
    Shipping_Agent>
    <Shipping_Agent_code>OLL</Shipping_Agent_code>
    <Shipping_Agent_name>ONE LINE LTD.</Shipping_Agent_name>
    </Shipping_Agent>
    <Exporter>
    <Exporter_name>${exporter[0].value}</Exporter_name>
    <Exporter_address>${exporterAddress[0].value}</Exporter_address>
    </Exporter>
    <Notify>
    <Notify_code>${notifyCode[0].value}</Notify_code>
    <Notify_name>${notifyParty[0].value}</Notify_name>
    <Notify_address>${notifyAddress[0].value}</Notify_address>
    </Notify>
    <Consignee>
    <Consignee_code>${consigneeCode[0].value}</Consignee_code>
    <Consignee_name>${consignee[0].value}</Consignee_name>
    <Consignee_address>${consigneeAddress[0].value}</Consignee_address>
    </Consignee>
    </Traders_segment>
    <ctn_segment>
    <Ctn_reference>${contPrefixes[0][0].value}${contNos[0][0].value}</Ctn_reference>
    <Number_of_packages>${quantity[0].value}</Number_of_packages>
    <Type_of_container>${contTypes[0][0].value}</Type_of_container>
    <Status>${statuses[0][0].value}</Status>
    <Seal_number>${sealNos[0][0].value}</Seal_number>
    <IMCO>${imcos[0][0].value}</IMCO>
    <UN>${uns[0][0].value}</UN>
    <Ctn_location>${portOfLanding[0].value}</Ctn_location>
    <Commodity_code>${commoCodes[0][0].value}</Commodity_code>
    <Gross_weight>${weightKgms[0][0].value}</Gross_weight>
    <Verified_Gross_Mass>${vgmQtys[0][0].value}</Verified_Gross_Mass>
    </ctn_segment>
    <Goods_segment>
    <Number_of_packages>${quantity[0].value}</Number_of_packages>
    <Package_type_code>${quantity2[0].value}</Package_type_code>
    <Gross_mass>${weightKgms[0][0].value}</Gross_mass>
    <Shipping_marks>${marks[0].value}</Shipping_marks>
    <Goods_description>${commodity[0].value}</Goods_description>
    <Volume_in_cubic_meters>${contVolumes[0][0].value}</Volume_in_cubic_meters>
    <Num_of_ctn_for_this_bol>${contNos.length.toString()}</Num_of_ctn_for_this_bol>
    <Remarks></Remarks>
    </Goods_segment>
    <Value_segment>
    <Freight_segment>
    <Freight_value>0</Freight_value>
    <Freight_currency>xxx</Freight_currency>
    </Freight_segment>
    </Value_segment>
    </Bol_segment>
 *
 * ----------------------------------------------------------------------------------------------------------------------------------------------------------------

    <Bol_segment>
    <Bol_id>
    <Bol_reference>ACENSACGP005625</Bol_reference>
    <Line_number>2</Line_number>
    <Bol_nature>23</Bol_nature>
    <Bol_type_code>HSB</Bol_type_code>
    <DG_status></DG_status>
    </Bol_id>
    <Consolidated_Cargo>0</Consolidated_Cargo>
    <Load_unload_place>
    <Port_of_origin_code>INNSA</Port_of_origin_code>
    <Place_of_unloading_code>BDCGP</Place_of_unloading_code>
    </Load_unload_place>
    <Traders_segment>
    <Carrier>
    <Carrier_code>301093439</Carrier_code>
    <Carrier_name>NOBLE SHIPPING LINE</Carrier_name>
    <Carrier_address>PORTLAND M A M TOWER(13TH FLOOR),STRAND ROAD,BANGLABAZAR,CHATTOGRAM</Carrier_address>
    </Carrier>
    <Shipping_Agent>
    Shipping_Agent>
    <Shipping_Agent_code>OLL</Shipping_Agent_code>
    <Shipping_Agent_name>ONE LINE LTD.</Shipping_Agent_name>
    </Shipping_Agent>
    <Exporter>
    <Exporter_name>PERFECT FILAMENTS LTD</Exporter_name>
    <Exporter_address>MAHARASHTRA,INDIA</Exporter_address>
    </Exporter>
    <Notify>
    <Notify_code>000368453-0103</Notify_code>
    <Notify_name>ECHOTEX LIMITED</Notify_name>
    <Notify_address>GAZIPUR,BANGLADESH</Notify_address>
    </Notify>
    <Consignee>
    <Consignee_code>000002689-0002</Consignee_code>
    <Consignee_name>STANDARD CHARTERED BANK</Consignee_name>
    <Consignee_address>DHAKA,BANGLADESH</Consignee_address>
    </Consignee>
    </Traders_segment>
    <ctn_segment>
    <Ctn_reference>HJLU1233475</Ctn_reference>
    <Number_of_packages>309</Number_of_packages>
    <Type_of_container>22G1</Type_of_container>
    <Status>FCL</Status>
    <Seal_number>000421</Seal_number>
    <IMCO></IMCO>
    <UN></UN>
    <Ctn_location></Ctn_location>
    <Commodity_code>35</Commodity_code>
    <Gross_weight>10700.21</Gross_weight>
    <Verified_Gross_Mass>12900.21</Verified_Gross_Mass>
    </ctn_segment>
    <Goods_segment>
    <Number_of_packages>309</Number_of_packages>
    <Package_type_code>CT</Package_type_code>
    <Gross_mass>10700.21</Gross_mass>
    <Shipping_marks>N/M</Shipping_marks>
    <Goods_description>100 PERCENT POLYESTER TEXTURED YARN. YARN FOR 100 PCT EXPORT
    75/36 SD NIM RECYCLE
    75/36 BLACK NIM</Goods_description>
    <Volume_in_cubic_meters>0</Volume_in_cubic_meters>
    <Num_of_ctn_for_this_bol>1</Num_of_ctn_for_this_bol>
    <Remarks></Remarks>
    </Goods_segment>
    <Value_segment>
    <Freight_segment>
    <Freight_value>0</Freight_value>
    <Freight_currency>xxx</Freight_currency>
    </Freight_segment>
    </Value_segment>
    </Bol_segment>

    ----------------------------------------------------------------------------------------------------------------------------------------------------------------


    <Bol_segment>
    <Bol_id>
    <Bol_reference>ACENSACGP005825</Bol_reference>
    <Line_number>3</Line_number>
    <Bol_nature>23</Bol_nature>
    <Bol_type_code>HSB</Bol_type_code>
    <DG_status></DG_status>
    </Bol_id>
    <Consolidated_Cargo>0</Consolidated_Cargo>
    <Load_unload_place>
    <Port_of_origin_code>INNSA</Port_of_origin_code>
    <Place_of_unloading_code>BDCGP</Place_of_unloading_code>
    </Load_unload_place>
    <Traders_segment>
    <Carrier>
    <Carrier_code>301093439</Carrier_code>
    <Carrier_name>NOBLE SHIPPING LINE</Carrier_name>
    <Carrier_address>PORTLAND M A M TOWER(13TH FLOOR),STRAND ROAD,BANGLABAZAR,CHATTOGRAM</Carrier_address>
    </Carrier>
    <Shipping_Agent>
    Shipping_Agent>
    <Shipping_Agent_code>OLL</Shipping_Agent_code>
    <Shipping_Agent_name>ONE LINE LTD.</Shipping_Agent_name>
    </Shipping_Agent>
    <Exporter>
    <Exporter_name>SOLAR CHEMFERTS PVT. LTD.</Exporter_name>
    <Exporter_address>MAHARASHTRA,INDIA</Exporter_address>
    </Exporter>
    <Notify>
    <Notify_code>004874779-1106</Notify_code>
    <Notify_name>AGRIVISION INTERNATIONAL</Notify_name>
    <Notify_address>BOGURA,BANGLADESH</Notify_address>
    </Notify>
    <Consignee>
    <Consignee_code>000000124-0002</Consignee_code>
    <Consignee_name>ISLAMI BANK BANGLADESH PLC</Consignee_name>
    <Consignee_address>BOGURA,BANGLADESH</Consignee_address>
    </Consignee>
    </Traders_segment>
    <ctn_segment>
    <Ctn_reference>CSLU1177879</Ctn_reference>
    <Number_of_packages>960</Number_of_packages>
    <Type_of_container>22G1</Type_of_container>
    <Status>FCL</Status>
    <Seal_number>U000255/SPPL03820410</Seal_number>
    <IMCO></IMCO>
    <UN></UN>
    <Ctn_location></Ctn_location>
    <Commodity_code>35</Commodity_code>
    <Gross_weight>24096</Gross_weight>
    <Verified_Gross_Mass>26296</Verified_Gross_Mass>
    </ctn_segment>
    <ctn_segment>
    <Ctn_reference>JZPU1107434</Ctn_reference>
    <Number_of_packages>960</Number_of_packages>
    <Type_of_container>22G1</Type_of_container>
    <Status>FCL</Status>
    <Seal_number>U000256/SPPL03820411</Seal_number>
    <IMCO></IMCO>
    <UN></UN>
    <Ctn_location></Ctn_location>
    <Commodity_code>35</Commodity_code>
    <Gross_weight>24096</Gross_weight>
    <Verified_Gross_Mass>26296</Verified_Gross_Mass>
    </ctn_segment>
    <Goods_segment>
    <Number_of_packages>1920</Number_of_packages>
    <Package_type_code>BG</Package_type_code>
    <Gross_mass>48192</Gross_mass>
    <Shipping_marks>N/M</Shipping_marks>
    <Goods_description>FUNGICIDE FOR AGRICULTURAL USE ONLY
    EGSUL 80WDG
    SULPHUR 80 PERCENT WDG</Goods_description>
    <Volume_in_cubic_meters>0</Volume_in_cubic_meters>
    <Num_of_ctn_for_this_bol>2</Num_of_ctn_for_this_bol>
    <Remarks></Remarks>
    </Goods_segment>
    <Value_segment>
    <Freight_segment>
    <Freight_value>0</Freight_value>
    <Freight_currency>xxx</Freight_currency>
    </Freight_segment>
    </Value_segment>
    </Bol_segment>

    ----------------------------------------------------------------------------------------------------------------------------------------------------------------


    <Bol_segment>
    <Bol_id>
    <Bol_reference>ACENSACGP005925</Bol_reference>
    <Line_number>4</Line_number>
    <Bol_nature>23</Bol_nature>
    <Bol_type_code>HSB</Bol_type_code>
    <DG_status></DG_status>
    </Bol_id>
    <Consolidated_Cargo>0</Consolidated_Cargo>
    <Load_unload_place>
    <Port_of_origin_code>INNSA</Port_of_origin_code>
    <Place_of_unloading_code>BDCGP</Place_of_unloading_code>
    </Load_unload_place>
    <Traders_segment>
    <Carrier>
    <Carrier_code>301093439</Carrier_code>
    <Carrier_name>NOBLE SHIPPING LINE</Carrier_name>
    <Carrier_address>PORTLAND M A M TOWER(13TH FLOOR),STRAND ROAD,BANGLABAZAR,CHATTOGRAM</Carrier_address>
    </Carrier>
    <Shipping_Agent>
    Shipping_Agent>
    <Shipping_Agent_code>OLL</Shipping_Agent_code>
    <Shipping_Agent_name>ONE LINE LTD.</Shipping_Agent_name>
    </Shipping_Agent>
    <Exporter>
    <Exporter_name>SOLAR CHEMFERTS PVT. LTD.</Exporter_name>
    <Exporter_address>MAHARASHTRA,INDIA</Exporter_address>
    </Exporter>
    <Notify>
    <Notify_code>006472244-1106</Notify_code>
    <Notify_name>NEWS CHAMICALS INDUSTRIES</Notify_name>
    <Notify_address>DHAKA,BANGLADESH</Notify_address>
    </Notify>
    <Consignee>
    <Consignee_code>000483356-0202</Consignee_code>
    <Consignee_name>NATIONAL CREDIT AND COMMERCE BANK PLC</Consignee_name>
    <Consignee_address>DHAKA,BANGLADESH</Consignee_address>
    </Consignee>
    </Traders_segment>
    <ctn_segment>
    <Ctn_reference>CSKU2362724</Ctn_reference>
    <Number_of_packages>960</Number_of_packages>
    <Type_of_container>22G1</Type_of_container>
    <Status>FCL</Status>
    <Seal_number>000424/SPPL03820413</Seal_number>
    <IMCO></IMCO>
    <UN></UN>
    <Ctn_location></Ctn_location>
    <Commodity_code>35</Commodity_code>
    <Gross_weight>24096</Gross_weight>
    <Verified_Gross_Mass>26296</Verified_Gross_Mass>
    </ctn_segment>
    <ctn_segment>
    <Ctn_reference>CBHU5844691</Ctn_reference>
    <Number_of_packages>960</Number_of_packages>
    <Type_of_container>22G1</Type_of_container>
    <Status>FCL</Status>
    <Seal_number>000430/SPPL03820414</Seal_number>
    <IMCO></IMCO>
    <UN></UN>
    <Ctn_location></Ctn_location>
    <Commodity_code>35</Commodity_code>
    <Gross_weight>24096</Gross_weight>
    <Verified_Gross_Mass>26296</Verified_Gross_Mass>
    </ctn_segment>
    <Goods_segment>
    <Number_of_packages>1920</Number_of_packages>
    <Package_type_code>BG</Package_type_code>
    <Gross_mass>48192</Gross_mass>
    <Shipping_marks>N/M</Shipping_marks>
    <Goods_description>FUNGICIDE FOR AGRICULTURAL USE ONLY:
    01.ITEM NAME: NEWSVIT 80 WDG(SULPHUR 80 PERCENT WDG)</Goods_description>
    <Volume_in_cubic_meters>0</Volume_in_cubic_meters>
    <Num_of_ctn_for_this_bol>2</Num_of_ctn_for_this_bol>
    <Remarks></Remarks>
    </Goods_segment>
    <Value_segment>
    <Freight_segment>
    <Freight_value>0</Freight_value>
    <Freight_currency>xxx</Freight_currency>
    </Freight_segment>
    </Value_segment>
    </Bol_segment>


    ----------------------------------------------------------------------------------------------------------------------------------------------------------------


    <Bol_segment>
    <Bol_id>
    <Bol_reference>ACENSACGP006025</Bol_reference>
    <Line_number>5</Line_number>
    <Bol_nature>23</Bol_nature>
    <Bol_type_code>HSB</Bol_type_code>
    <DG_status></DG_status>
    </Bol_id>
    <Consolidated_Cargo>0</Consolidated_Cargo>
    <Load_unload_place>
    <Port_of_origin_code>INNSA</Port_of_origin_code>
    <Place_of_unloading_code>BDCGP</Place_of_unloading_code>
    </Load_unload_place>
    <Traders_segment>
    <Carrier>
    <Carrier_code>301093439</Carrier_code>
    <Carrier_name>NOBLE SHIPPING LINE</Carrier_name>
    <Carrier_address>PORTLAND M A M TOWER(13TH FLOOR),STRAND ROAD,BANGLABAZAR,CHATTOGRAM</Carrier_address>
    </Carrier>
    <Shipping_Agent>
    Shipping_Agent>
    <Shipping_Agent_code>OLL</Shipping_Agent_code>
    <Shipping_Agent_name>ONE LINE LTD.</Shipping_Agent_name>
    </Shipping_Agent>
    <Exporter>
    <Exporter_name>SOLAR CHEMFERTS PVT. LTD.</Exporter_name>
    <Exporter_address>MAHARASHTRA,INDIA</Exporter_address>
    </Exporter>
    <Notify>
    <Notify_code>001760054-0103</Notify_code>
    <Notify_name>EVERGREEN CROP CARE LIMITED</Notify_name>
    <Notify_address>DHAKA,BANGLADESH</Notify_address>
    </Notify>
    <Consignee>
    <Consignee_code>000000275-0002</Consignee_code>
    <Consignee_name>BANK ASIA LTD</Consignee_name>
    <Consignee_address>DHAKA,BANGLADESH</Consignee_address>
    </Consignee>
    </Traders_segment>
    <ctn_segment>
    <Ctn_reference>TEMU4563287</Ctn_reference>
    <Number_of_packages>960</Number_of_packages>
    <Type_of_container>22G1</Type_of_container>
    <Status>FCL</Status>
    <Seal_number>000681/SPPL03820412</Seal_number>
    <IMCO></IMCO>
    <UN></UN>
    <Ctn_location></Ctn_location>
    <Commodity_code>35</Commodity_code>
    <Gross_weight>24096</Gross_weight>
    <Verified_Gross_Mass>26296</Verified_Gross_Mass>
    </ctn_segment>
    <Goods_segment>
    <Number_of_packages>960</Number_of_packages>
    <Package_type_code>BG</Package_type_code>
    <Gross_mass>24096</Gross_mass>
    <Shipping_marks>N/M</Shipping_marks>
    <Goods_description>EVERSULF 80 DF (SULPHUR 80 DF)
    FUNGICIDE FOR AGRICULTUTAL USE</Goods_description>
    <Volume_in_cubic_meters>0</Volume_in_cubic_meters>
    <Num_of_ctn_for_this_bol>1</Num_of_ctn_for_this_bol>
    <Remarks></Remarks>
    </Goods_segment>
    <Value_segment>
    <Freight_segment>
    <Freight_value>0</Freight_value>
    <Freight_currency>xxx</Freight_currency>
    </Freight_segment>
    </Value_segment>
    </Bol_segment>


    ----------------------------------------------------------------------------------------------------------------------------------------------------------------


    <Bol_segment>
    <Bol_id>
    <Bol_reference>ALSCON-00257</Bol_reference>
    <Line_number>6</Line_number>
    <Bol_nature>23</Bol_nature>
    <Bol_type_code>HSB</Bol_type_code>
    <DG_status></DG_status>
    </Bol_id>
    <Consolidated_Cargo>0</Consolidated_Cargo>
    <Load_unload_place>
    <Port_of_origin_code>INNSA</Port_of_origin_code>
    <Place_of_unloading_code>BDCGP</Place_of_unloading_code>
    </Load_unload_place>
    <Traders_segment>
    <Carrier>
    <Carrier_code>301093439</Carrier_code>
    <Carrier_name>NOBLE SHIPPING LINE</Carrier_name>
    <Carrier_address>PORTLAND M A M TOWER(13TH FLOOR),STRAND ROAD,BANGLABAZAR,CHATTOGRAM</Carrier_address>
    </Carrier>
    <Shipping_Agent>
    Shipping_Agent>
    <Shipping_Agent_code>OLL</Shipping_Agent_code>
    <Shipping_Agent_name>ONE LINE LTD.</Shipping_Agent_name>
    </Shipping_Agent>
    <Exporter>
    <Exporter_name>ROSSARI BIOTECH LIMITED</Exporter_name>
    <Exporter_address>MUMBAI,INDIA</Exporter_address>
    </Exporter>
    <Notify>
    <Notify_code>000192848-0103</Notify_code>
    <Notify_name>TUSUKA PROCESSING LTD.</Notify_name>
    <Notify_address>GAZIPUR,BANGLADESH</Notify_address>
    </Notify>
    <Consignee>
    <Consignee_code>000000839-0002</Consignee_code>
    <Consignee_name>UTTARA BANK PLC</Consignee_name>
    <Consignee_address>DHAKA,BANGLADESH</Consignee_address>
    </Consignee>
    </Traders_segment>
    <ctn_segment>
    <Ctn_reference>FSCU7789570</Ctn_reference>
    <Number_of_packages>715</Number_of_packages>
    <Type_of_container>22G1</Type_of_container>
    <Status>FCL</Status>
    <Seal_number>008182</Seal_number>
    <IMCO></IMCO>
    <UN></UN>
    <Ctn_location></Ctn_location>
    <Commodity_code>35</Commodity_code>
    <Gross_weight>25132.25</Gross_weight>
    <Verified_Gross_Mass>27332.25</Verified_Gross_Mass>
    </ctn_segment>
    <ctn_segment>
    <Ctn_reference>MSCU3231165</Ctn_reference>
    <Number_of_packages>715</Number_of_packages>
    <Type_of_container>22G1</Type_of_container>
    <Status>FCL</Status>
    <Seal_number>006463</Seal_number>
    <IMCO></IMCO>
    <UN></UN>
    <Ctn_location></Ctn_location>
    <Commodity_code>35</Commodity_code>
    <Gross_weight>25132.25</Gross_weight>
    <Verified_Gross_Mass>27332.25</Verified_Gross_Mass>
    </ctn_segment>
    <Goods_segment>
    <Number_of_packages>1430</Number_of_packages>
    <Package_type_code>PK</Package_type_code>
    <Gross_mass>50264.5</Gross_mass>
    <Shipping_marks>N/M</Shipping_marks>
    <Goods_description>CHEMICAL FOR 100 PCT EXPORT ORIENTED RMG WASHING INDUSTRY:
    SODA ASH (GREENSODA 1000 POWDER)</Goods_description>
    <Volume_in_cubic_meters>0</Volume_in_cubic_meters>
    <Num_of_ctn_for_this_bol>2</Num_of_ctn_for_this_bol>
    <Remarks></Remarks>
    </Goods_segment>
 */
